"""add_brand_to_products

Revision ID: 3feba76987ac
Revises: 08e5f3ef4ba3
Create Date: 2026-06-07 12:08:33.832067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3feba76987ac'
down_revision: Union[str, None] = '08e5f3ef4ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
