"""add_account_id_to_collections

Revision ID: 4639568363ac
Revises: 3feba76987ac
Create Date: 2026-06-07 14:38:37.590129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4639568363ac'
down_revision: Union[str, None] = '3feba76987ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('account_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_collections_account_id'), 'collections', ['account_id'], unique=False)
    op.create_foreign_key('fk_collections_accounts', 'collections', 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_collections_accounts', 'collections', type_='foreignkey')
    op.drop_index(op.f('ix_collections_account_id'), table_name='collections')
    op.drop_column('collections', 'account_id')
    # ### end Alembic commands ###
