"""invoices_collections

Revision ID: dbe8d5470c69
Revises: 0003_people_routes
Create Date: 2026-06-04 22:34:01.555811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe8d5470c69'
down_revision: Union[str, None] = '0003_people_routes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('dsr_id', sa.UUID(), nullable=True),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIAL', 'PAID', 'VOID', name='invoice_status_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dsr_id'], ['dsrs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_date'), 'invoices', ['date'], unique=False)
    op.create_index(op.f('ix_invoices_dealer_id'), 'invoices', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_invoices_dsr_id'), 'invoices', ['dsr_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_shop_id'), 'invoices', ['shop_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('dsr_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BKASH', 'NAGAD', 'ROCKET', 'BANK_TRANSFER', 'CHEQUE', name='payment_method_enum'), nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dsr_id'], ['dsrs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_collected_at'), 'collections', ['collected_at'], unique=False)
    op.create_index(op.f('ix_collections_dealer_id'), 'collections', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_collections_dsr_id'), 'collections', ['dsr_id'], unique=False)
    op.create_index(op.f('ix_collections_invoice_id'), 'collections', ['invoice_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty_carton', sa.Integer(), nullable=False),
    sa.Column('qty_pcs', sa.Integer(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_free_item', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.drop_constraint(op.f('dealers_phone_key'), 'dealers', type_='unique')
    op.drop_index(op.f('ix_dealers_route_id'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_phone'), table_name='dealers')
    op.create_index(op.f('ix_dealers_phone'), 'dealers', ['phone'], unique=True)
    op.drop_constraint(op.f('dsrs_phone_key'), 'dsrs', type_='unique')
    op.drop_index(op.f('ix_dsrs_route_id'), table_name='dsrs')
    op.drop_index(op.f('ix_dsrs_phone'), table_name='dsrs')
    op.create_index(op.f('ix_dsrs_phone'), 'dsrs', ['phone'], unique=True)
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_index(op.f('ix_purchases_date'), table_name='purchases')
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.drop_index(op.f('ix_shops_dealer_id'), table_name='shops')
    op.drop_index(op.f('ix_stock_movements_date'), table_name='stock_movements')
    op.create_index(op.f('ix_stock_movements_movement_date'), 'stock_movements', ['movement_date'], unique=False)
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.drop_index(op.f('ix_stock_movements_movement_date'), table_name='stock_movements')
    op.create_index(op.f('ix_stock_movements_date'), 'stock_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_shops_dealer_id'), 'shops', ['dealer_id'], unique=False)
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.create_index(op.f('ix_purchases_date'), 'purchases', ['purchase_date'], unique=False)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.drop_index(op.f('ix_dsrs_phone'), table_name='dsrs')
    op.create_index(op.f('ix_dsrs_phone'), 'dsrs', ['phone'], unique=False)
    op.create_index(op.f('ix_dsrs_route_id'), 'dsrs', ['route_id'], unique=False)
    op.create_unique_constraint(op.f('dsrs_phone_key'), 'dsrs', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_dealers_phone'), table_name='dealers')
    op.create_index(op.f('ix_dealers_phone'), 'dealers', ['phone'], unique=False)
    op.create_index(op.f('ix_dealers_route_id'), 'dealers', ['route_id'], unique=False)
    op.create_unique_constraint(op.f('dealers_phone_key'), 'dealers', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_collections_invoice_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_dsr_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_dealer_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_collected_at'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_shop_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_dsr_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_dealer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_date'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
